services:
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:latest
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=admin123
    ports:
      - 27017:27017
